name = "gridsheet-storybook"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"
watch_dir = "stories"

[build.upload]
format = "directory"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
