name = "gridsheet"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm build"

[build.upload]
format = "directory"
dir = "out"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
