export {
  useState,
  useReducer,
  useEffect,
  useLayoutEffect,
  useRef,
  useImperativeHandle,
  useMemo,
  useCallback,
  useContext,
  useDebugValue,
  createElement,
  createContext,
  createRef,
  Fragment,
  Component,
  version,
  Children,
  render as compatRender,
  hydrate,
  unmountComponentAtNode,
  createPortal,
  createFactory,
  cloneElement,
  isValidElement,
  findDOMNode,
  PureComponent,
  memo,
  forwardRef,
  unstable_batchedUpdates,
  StrictMode,
  Suspense,
  SuspenseList,
  lazy,
} from 'preact/compat';
