name: build
on:
  - push

jobs:
  release:
    # needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    name: npm upload
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "14"

      - name: cache
        uses: actions/cache@v2.1.1
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: upload
        run: |
          npm install
          npm run build
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm publish || true
