name: typecheck
on:
  push:
  workflow_dispatch:

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: install
        run: |
          yarn install
      - name: check
        run: |
          yarn run tsc
