name: test
on:
  - push

jobs:
  build-storybook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "14" # 16
      - name: cache
        uses: actions/cache@v2.1.1
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: build
        run: |
          yarn install
          yarn run build-storybook

  run-tests:
    runs-on: ubuntu-latest
    container:
      image: nginx:1.23.2
      env:
        NGINX_PORT: 5233
      volumes:
        - ./storybook-static:/usr/share/nginx/html
    steps:
      - name: test
        run: ls storybook-static
      - name: test2
        run: wget http://localhost:5233/?path=/story/basic--small
